apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8085
    volumeMounts: 
    - name: webcontainer
      mountPath: "/app_01/"
  volume:
  - name: webcontainer
    persistentVolumeClaim:
      claimName: pvc-nfs-data    
