apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31000
  selector:
    app: todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      initContainers:
      - name: check-db
        image: busybox
        command: ['/bin/sh']
        args: ['-c', 'until nc -z mysql-normal 3306; do echo waiting for DBservice; sleep 5; done;']
      containers:
      - name: python-todo
        image: kunchalavikram/python_todo_app:v2
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URI
          value: 'mysql+pymysql://root:root@mysql-normal.default.svc.cluster.local:3306/todo'
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          tcpSocket:
            port: 5000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 8
          tcpSocket:
            port: 5000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 8
          tcpSocket:
            port: 5000