apiVersion: v1
kind: Pod 
metadata:
  name: python-flask
  labels:
    name: python-flask
spec:
  containers:
  - name: python-flask
    image: ghalge/python_flask-docker-smaple:1
    ports:
    - containerPort: 8080
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      exec:
        command:
        - /bin/bash
        - -c 
        - ps -ef | grep app
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 5
      exec:
        command:
        - /bin/bash
        - -c
        - curl http://localhost:8080
