apiVersion: app/v1
kind: Deployment 
metadata:
  name: application-nginx
  labels:
    app: application-nginx
spec:
  replicas: 1
  selector:
    matchlabels:
      app: application-nginx
  template:
    metadata:
      labels:
        app: application-nginx
  spec:
    containers:
    - name: application-nginx
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 8443
        protocol: TCP
      readinessProbe:
        initialDelaySeconds: 1
        periodSeconds: 5
        timeoutSeconds: 1
        exec:
          command:
          - cat
          - /etc/nginx/nginx.conf